name: comicwrap_f
description: An open source webcomic reader and tracker for Android and iOS

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.2
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.4
  cloud_functions: ^3.0.3
  google_sign_in: ^5.0.1
  flutter_signin_button: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  rxdart: ^0.27.0
  flutter_cache_manager: ^3.0.1
  webview_flutter: ^3.0.0
  universal_io: ^2.0.4
  flutter_easyloading: ^3.0.0
  timeago: ^3.1.0
  flutter_riverpod: ^1.0.3
  url_launcher: ^6.0.9
  badges: ^2.0.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  json_annotation: ^4.3.0
  freezed_annotation: ^1.1.0
  palette_generator: ^0.3.2
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^6.0.0
  freezed: ^1.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^5.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - integration_test/assets/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_white.png"
