default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Internal Testing track"
  lane :internal do
    upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        release_status: "draft",
        json_key_data: ENV['FASTLANE_SERVICE_ACCOUNT_KEY']
        )
  end
end
