default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Internal Testing track"
  lane :internal do
    sh "flutter build appbundle -v"
    upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        )
  end
end
