name: Main Build Pipeline

# Controls when the action will run.
on:
  push:
    paths:
      - ".github/workflows/app-build.yml"
      - ".github/actions/setup-flutter-build/**"
      - "lib/**"
      - "assets/**"
      - "android/**"
      - "ios/**"
      - "test/**"
      - "integration_test/**"
      - "test_driver/**"
      - "pubspec.lock"
      - "pubspec.yaml"
      - "build.yaml"

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Set build name conditionally
      - name: Set Build name
        run: |
          case $GITHUB_REF in
            "refs/tags/"*) echo "BUILD_NAME=${GITHUB_REF/refs\/tags\/v}" >> $GITHUB_ENV ;;
            *) echo "BUILD_NAME=$GITHUB_REF" >> $GITHUB_ENV ;;
          esac
      # Write decoded secrets files
      - name: Secret google-services.json to file
        run: echo $GOOGLE_SERVICES_ANDROID | base64 --decode > android/app/google-services.json
        env:
          GOOGLE_SERVICES_ANDROID: ${{ secrets.GOOGLE_SERVICES_ANDROID }}
      - name: Decode Play Store Upload Key to Keyfile
        run: echo $PLAY_STORE_UPLOAD_KEY | base64 --decode > android/app/upload-keystore.jks
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
      - name: Secret key.properties to file
        run: echo $ANDROID_KEY_PROPERTIES | base64 --decode > android/key.properties
        env:
          ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
      - name: Append AdMob App ID to local.properties
        run: printf $ANDROID_ADMOB_APPID >> android/local.properties
        env:
          ANDROID_ADMOB_APPID: ${{ secrets.ANDROID_ADMOB_APPID }}
      # Setup required tools
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.8.0
      # Run build with build number added for Google Play
      - uses: ./.github/actions/setup-flutter-build
      - name: Build AppBundle
        run: |
          flutter build appbundle -v --build-name=$BUILD_NAME \
          --build-number=${{github.run_number}} \
          --dart-define AD_ID_LIBRARY_BANNER_BOT=$AD_ID_LIBRARY_BANNER_BOT \
          --dart-define AD_ID_COMIC_WEB_PAGE_INTERSTITIAL=$AD_ID_COMIC_WEB_PAGE_INTERSTITIAL
        env:
          AD_ID_LIBRARY_BANNER_BOT: ${{ secrets.ANDROID_AD_ID_LIBRARY_BANNER_BOT }}
          AD_ID_COMIC_WEB_PAGE_INTERSTITIAL: ${{ secrets.ANDROID_AD_ID_COMIC_WEB_PAGE_INTERSTITIAL }}

      # Run Fastlane upload if a tagged version
      - name: Setup Fastlane (Ruby)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.2"
          bundler-cache: true
          working-directory: android
      - run: bundle exec fastlane internal
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          FASTLANE_SERVICE_ACCOUNT_KEY: ${{ secrets.FASTLANE_SERVICE_ACCOUNT_KEY }}
        working-directory: android
