name: Build and release tagged version to Google Play Internal Testing

# Controls when the action will run.
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Secret google-services.json to file
        run: echo $GOOGLE_SERVICES_ANDROID | base64 --decode > android/app/google-services.json
        env:
          GOOGLE_SERVICES_ANDROID: ${{ secrets.GOOGLE_SERVICES_ANDROID }}

      - name: Decode Play Store Upload Key to Keyfile
        run: echo $PLAY_STORE_UPLOAD_KEY | base64 --decode > android/app/upload-keystore.jks
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}

      - name: Secret key.properties to file
        run: echo $ANDROID_KEY_PROPERTIES | base64 --decode > android/key.properties
        env:
          ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.3

      - name: Setup Fastlane (Ruby)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
          working-directory: android

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Run build_runner Codegen
        run: flutter pub run build_runner build

      - name: Run flutter_launcher_icons
        run: flutter pub run flutter_launcher_icons:main

#      - name: Run Flutter Tests
#        run: flutter test

      - name: Build AppBundle
        run: flutter build appbundle -v --build-name=${GITHUB_REF/refs\/tags\/v} --build-number=${{github.run_number}}

      - run: bundle exec fastlane internal
        env:
          FASTLANE_SERVICE_ACCOUNT_KEY: ${{ secrets.FASTLANE_SERVICE_ACCOUNT_KEY }}
        working-directory: android
