name: Test

# Controls when the action will run. 
on:
  push:
  
  pull_request:
    branches: [ main ]

jobs:
  test_appengine:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.x
      
      - run: npm test
        working-directory: ./service_scrape-comic
